# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: my stock alert

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 23 * * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml
        pip install pandas
        pip install tushare
        
    - name: get real time stock info and print alert info
      run: 
        python ./real_time_stock_info.py c0641675f20fa1b0c0787235e132a60a1242a89bdf953952773d71e5
      env:
        tushare_token: ${{secrets.tushare_token}}
